version: '3.8'

services:
  database:
    build:
      context: ./
      dockerfile: Dockerfile.db
    command: --default-authentication-plugin=mysql_native_password
    image: database_image
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - shared_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    depends_on:
      database:
        condition: service_healthy
    build:
      context: ./
      dockerfile: Dockerfile.api
    image: api_image
    container_name: api
    restart: unless-stopped
    environment:
       NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - shared_network
    

  react:
    build:
      context: ./frontend
      dockerfile: dockerfile.react
    image: react_image
    container_name: react
    ports:
      - 3006:3006
    networks:
      - shared_network
    

networks:
  shared_network:
    driver: bridge